services:
  - type: worker
    name: telegram-group-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production

      - key: BOT_TOKEN
        value: "7243808108:AAFxlT-1HQ6twyVewzWqgdEgXd0EK_j4o5Y"

      - key: DEVELOPER_ID
        value: "7411444902"

      - key: SUPABASE_URL
        value: ""

      - key: SUPABASE_KEY
        value: ""

      - key: PORT
        value: "3000"