services:
  - type: web
    name: telegram-group-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DEVELOPER_ID
        sync: false
